version: "3.9"
services:
  server:
    image: ghcr.io/zhongfuze/data_process:main
    container_name: data_process
    volumes:
      - ./shared_data:/app/data
      - ./app/config:/app/config
      - ./app/log:/app/log
    network_mode: "host"
  loopup-gno:
    image: ghcr.io/zhongfuze/lookup-gno:main
    container_name: loopup_gno
    volumes:
      - ./nodejs_app:/nodejs_app
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ~/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/app/nginx/conf.d:/etc/nginx/conf.d
      - ~/app/nginx/logs:/var/log/nginx
      - ~/app/nginx/ssl:/etc/ssl
    network_mode: "host"
