[server]
server_name = "data_process"
ip = "127.0.0.1"
port = 11111
work_path = "/app"
thread_count = 8
process_count = 4
log_path = "/app/log"
log_level = 1
log_max_size = 1600

[pg_dsn]
keybase = "postgresql://postgres:password@host/dbname"
gnosis = "postgresql://postgres:password@host/dbname"
firefly = "postgresql://postgres:password@host/dbname"
clusters = "postgresql://postgres:password@host/dbname"
ens = "postgresql://postgres:password@host/dbname"

[id_allocation]
url = "http://id_allocation_hostname"

[datacloud_api]
url = "https://api.chainbase.online/v1/dw/query"
api_key = "123456abcdefgh6789abcdefgh"

[chainbase_api]
url = "https://api.chainbase.com/api/v1"
api_key = "123456abcdefgh6789abcdefgh"

[crossbell_api]
graphql = "https://indexer.crossbell.io/v1/graphql"
api = "https://indexer.crossbell.io/v1"

[rpc_url]
polygon = "https://rpc-mainnet.maticvigil.com"

[warpcast]
token = "warpcast.token"

[gnosisscan]
api_key = "123456abcdefgh6789abcdefgh"
